{% set name = "fletcher" %}
{% set version = "0.2.0" %}
{% set sha256 = "7549508cff74fdfd0b2af952a72c19eccdadb27d38dab0d3d060d350ae583314" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -m pip install --no-deps --ignore-installed .
  noarch: python

requirements:
  host:
    - python
    - pip
    - numba
    - pandas >=0.23
    - pyarrow >=0.9
    - setuptools_scm
    - six
  run:
    - numba
    - python
    - pandas >=0.23
    - pyarrow >=0.9
    - six

test:
  imports:
    - fletcher

about:
  home: https://github.com/xhochy/fletcher
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Pandas ExtensionDType/Array backed by Apache Arrow'
  doc_url: https://fletcher.readthedocs.io/

extra:
  recipe-maintainers:
    - xhochy
    - fjetter
