travis:
  secure:
    BINSTAR_TOKEN: bI09JplKkCn3AfK6UDc9NnrF0VonmuW3W7XHgbE3Hj+3onqORh6mlinhiegTtxBzBz72Kg0INwtNNT1Dd0mG+Oc6MQzsFihqUiaOxe/+tmXSxJyWRt9JZhJbz0KzDyuR1CAdtyJGDePpPCbH8CKTU3HHXuB5ZAJcnQN7+W+fvLOYtTMd1Lwv4GyhLkS5LA9Zl6etOQnKgRTzl+g4xQjUDg3sHGuvfQ5Vj4zGbDQjUlmei5++CGJ1xbhk8jJua6Kt+dF0GgcOju8NdSLhuV/fi6XlYU2mp1/+85/8Lt7uGNkalnovrD2S84Zae5QcdsT2YQ4iMt4vuCw8UJpfi0c4KYjJz6mKKPoQIEaoR5zf60XKHhh9DO9qia6rD2sEYiAtp6TJ+tYuBvfrtlAywUtC0WbGuHIH8PcXecU/bzi9vKcrcsbgThRYOUJ9e6rkdfdqDPFQo9VksKXl1sLu6/Qlm2FaTjMeCG8Rvg87wefnDkVszvFuQoVGKq/7rRMFZ/PovjkT8w3lZaeXmAf3Kl+vDC5+FDl9Ed4zKIwi02foM6dZEOtOHJCUN09c+d1TmsOg/YcynqBlhSmgQ6Hi1oM5d9VEW75Gzn1AgPbbF0TXtq2fFjIv3BdwjLcghEXrVDDkVqAlHG8/itB5VQBTpXDAiwvd14TQDOSM2xGlwb/30Ec=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
