travis:
  secure:
    BINSTAR_TOKEN: bZ5fMHpF3b2cLAPuUwCBdLCV0p8RkEqwjC8omMQ/5AeojAKRriiAFq1Mfx6UaJzPJnCFmL06VxDtic7QKC6uVvAasII0KxzBar34VboBwaKzsLaMohVhOPYe+tLIhjPdCcGREPkclVo/3ikqoiHTFfPszfM9Yw/UHLx2rskBTuQcEVHA8x8tTr/tEB0rT71cWe+n800/TxVZuQVWfr/KlTngyHPC1nkfdKfbbgv3VQEtzKh1hf8LXiepufszNfqnC/99l3Swg+U+2RRV63RQbb/uWH+QA58NIE7EpOYAWB8A9DWSzKcIK/jf58wAKDSE1muf2IVKhXuzNIncj8v87FmmBvch8MTU1Dr2Gr1Ux8rHKSJpDB5boshJHv7XMjJJfSrJXZuW7WEG/Jkyl1AC0tZ651pxda1em7Hhh0c2D3SVOwBXksjnR8S7Tv28XggVG1TUcGizas8hJOr3JMO6i6YtcKEV3KWvzsOnGEh0TMlpo0bG0GXHaVeDnYjlBQ10oFecxaZhcwqTCXM4zhabvJd9nSv+g6x4dF0UIWOoMVoEcFmaNHTf0LVT73dP3ZwslLQuJ5b7TfVwDLYEcUP5LMa5r1qNA7BLctP2Me3pAi/bci5DV2dEXNDdBkSZCjdcv8UsZfmM/OfJVo2T24rbFemFi3jQtg5o0V/6aLJasPA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
